name: neetu
favicon: null
layout_spectrum: 0.006619435967877507
typography_spectrum: 0.26176
title: neetu graphics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f0f0'
    - '#6b492f'
    - '#100604'
    - '#b76d4f'
    - '#c3cbda'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
